Repository kubeflow/fairing, pull requests merged in 2018-11, with the labels that each got.

#14 add r2d4 to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#17 Update readme & url in setup.py
  README.md
  setup.py
Labels: approved, lgtm, size/S

#19 Fix licence classifier in setup.py
  setup.py
Labels: approved, lgtm, size/XS

#18 Add Python2 support
  .gitignore
  Dockerfile.dev
  Makefile
  README.md
  examples/kubeflow-jupyter-notebook/TfJob.ipynb
  examples/simple-training/main.py
  fairing/__init__.py
  fairing/architectures/architecture.py
  fairing/architectures/kubeflow/basic.py
  fairing/architectures/kubeflow/distributed.py
  fairing/architectures/native/basic.py
  fairing/backend/__init__.py
  fairing/backend/backend.py
  fairing/backend/kubeflow.py
  fairing/backend/native.py
  fairing/builders/__init__.py
  fairing/builders/builder.py
  fairing/builders/container_image_builder.py
  fairing/builders/docker_builder.py
  fairing/builders/dockerfile.py
  fairing/builders/knative/__init__.py
  fairing/builders/knative/knative.py
  fairing/builders/knative/models/build.py
  fairing/builders/knative/models/build_template.py
  fairing/metaparticle.py
  fairing/notebook_helper.py
  fairing/options.py
  fairing/serve.py
  fairing/strategies/__init__.py
  fairing/strategies/basic.py
  fairing/strategies/hp.py
  fairing/strategies/pbt/__init__.py
  fairing/strategies/pbt/exploit.py
  fairing/strategies/pbt/explore.py
  fairing/strategies/pbt/pbt.py
  fairing/train.py
  fairing/utils.py
  setup.py
  tests/builders/knative/models/test_build.py
  tests/builders/test_builder.py
  tests/builders/test_dockerfile.py
  tests/test_architecture/test_native/test_basic_arch.py
  tests/test_strategies/test_basic_strat.py
  tests/test_train.py
  tests/test_utils.py
Labels: approved, lgtm, size/L
