Repository kubeflow/fairing, pull requests merged in 2019-09, with the labels that each got.

#362 Azure backend to work in custom namespaces
  fairing/backends/backends.py
  fairing/builders/cluster/azurestorage_context.py
Labels: approved, lgtm, ok-to-test, size/S

#346 Update docstrings under kubernetes and functions
  fairing/functions/function_shim.py
  fairing/http_utils.py
  fairing/kubernetes/manager.py
  fairing/kubernetes/utils.py
  fairing/utils.py
Labels: approved, lgtm, size/L

#365 Changes for Base_image comming from a private docker registry on GCP …
  fairing/backends/backends.py
  fairing/cloud/docker.py
  fairing/constants/constants.py
  tests/unit/cloud/test_docker.py
Labels: approved, lgtm, ok-to-test, size/M

#378 update kubeflow-fairing version to 0.6.0
  kubeflow/fairing/__init__.py
  setup.py
Labels: approved, lgtm, size/XS

#374 Add aws examples
  examples/aws/backend.ipynb
  examples/aws/ecr.ipynb
  examples/aws/train.ipynb
  examples/prediction/xgboost-high-level-apis.ipynb
Labels: approved, lgtm, size/L

#372 Add service_type in serving deployer for aws
  kubeflow/fairing/backends/backends.py
Labels: approved, lgtm, size/XS

#351 option to select tfjob version + adding annotation parameter
  kubeflow/fairing/constants/constants.py
  kubeflow/fairing/deployers/job/job.py
  kubeflow/fairing/kubernetes/manager.py
Labels: approved, lgtm, ok-to-test, size/S

#379 cluster builder should use a job not a pod #349
  kubeflow/fairing/builders/cluster/cluster.py
Labels: approved, lgtm, ok-to-test, size/M

#377 Fix python compatibility issue
  kubeflow/fairing/functions/function_shim.py
  kubeflow/fairing/preprocessors/function.py
  tests/integration/common/test_py_version_checking.py
Labels: approved, lgtm, size/S

#376 Use service type ClusterIP by default
  examples/prediction/xgboost-high-level-apis.ipynb
  kubeflow/fairing/backends/backends.py
  kubeflow/fairing/deployers/serving/serving.py
  kubeflow/fairing/ml_tasks/tasks.py
Labels: approved, lgtm, size/S

#354 generate docstring for config, deplyer, frameworks
  kubeflow/fairing/config.py
  kubeflow/fairing/deployers/deployer.py
  kubeflow/fairing/deployers/gcp/gcp.py
  kubeflow/fairing/deployers/gcp/gcpserving.py
  kubeflow/fairing/deployers/job/job.py
  kubeflow/fairing/deployers/kfserving/kfserving.py
  kubeflow/fairing/deployers/serving/serving.py
  kubeflow/fairing/deployers/tfjob/tfjob.py
  kubeflow/fairing/frameworks/lightgbm.py
  kubeflow/fairing/frameworks/utils.py
Labels: approved, lgtm, ok-to-test, size/L
