Repository kubeflow/fairing, pull requests merged in 2019-11, with the labels that each got.

#410 disable xgboost_high_level_api notebook run temproarily
  tests/integration/gcp/test_running_in_notebooks.py
Labels: approved, lgtm, size/S

#407 Enhance kfserving integration
  examples/kfserving/main.py
  kubeflow/fairing/constants/constants.py
  kubeflow/fairing/deployers/kfserving/kfserving.py
  kubeflow/fairing/kubernetes/manager.py
  requirements.txt
  tests/unit/deployers/kfserving.py
Labels: approved, lgtm, size/L

#406 Add annotations param to TfJob
  kubeflow/fairing/deployers/tfjob/tfjob.py
Labels: approved, lgtm, ok-to-test, size/XS

#412 release kubeflow-fairing 0.7 and add doc links
  README.md
  kubeflow/fairing/__init__.py
  setup.py
Labels: approved, lgtm, size/S

#415 update kfserving version
  requirements.txt
  setup.py
Labels: approved, lgtm, size/XS

#414 Fixed xgboost run in notebook test
  .gitignore
  kubeflow/fairing/kubernetes/manager.py
  tests/integration/gcp/test_running_in_notebooks.py
Labels: approved, lgtm, size/M

#423 Test PyPI pre-releases but allow for failures
  .travis.yml
Labels: approved, lgtm, ok-to-test, size/S

#420 fix logical bug
  kubeflow/fairing/backends/backends.py
Labels: approved, lgtm, size/XS

#419 Add a simple fairing job example by using private-registry on Jupyter-notebook.
  examples/notebook/hello-world-with-private-registry.ipynb
Labels: approved, lgtm, ok-to-test, size/L

#427 Update kaniko image from version v0.7.0 to 0.14.0
  kubeflow/fairing/constants/constants.py
Labels: approved, lgtm, ok-to-test, size/XS
