Repository kubeflow/fairing, pull requests merged in 2019-01, with the labels that each got.

#50 avoid launching both chief and worker pods when running a non distributed job
  fairing/training/kubeflow/decorators.py
  fairing/training/kubeflow/deployment.py
  setup.py
Labels: approved, lgtm, needs-ok-to-test, size/S

#56 tests: fix tests
  tests/builders/test_dockerfile.py
Labels: approved, lgtm, size/XS

#58 deploy: optionally print out manifests
  fairing/training/native/decorators.py
  fairing/training/native/deployment.py
Labels: approved, lgtm, size/S

#55 notebook_helper: remove magic commands
  fairing/notebook_helper.py
  tests/test_notebook_helper.py
  tests/testdata/magic_command.ipynb
Labels: approved, lgtm, size/L

#59 Update deps
  setup.py
Labels: approved, lgtm, size/XS

#60 Adding myself to the reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#61 update tfjob to v1beta1
  fairing/backend/kubernetes/manager.py
  fairing/training/kubeflow/deployment.py
Labels: approved, lgtm, size/XS

#62 Refactored tfjob version, optional output, added resource_limits
  fairing/backend/kubernetes/__init__.py
  fairing/backend/kubernetes/manager.py
  fairing/builders/append/append.py
  fairing/training/kubeflow/deployment.py
  fairing/training/native/deployment.py
Labels: approved, lgtm, needs-ok-to-test, size/L
