Repository kubeflow/fairing, pull requests merged in 2019-05, with the labels that each got.

#226 Added tests for converted notebook preprocessor
  tests/unit/preprocessors/test_converted_notebook_preprocessor.py
Labels: approved, lgtm, size/M

#238 Adding fairing specific user agent to GCP calls
  Dockerfile.test
  cloudbuild.yaml
  fairing/__init__.py
  fairing/constants/constants.py
  fairing/deployers/gcp/gcp.py
  fairing/deployers/gcp/gcpserving.py
  fairing/deployers/tfjob/tfjob.py
  fairing/http_utils.py
  tests/integration/gcp/conftest.py
  tests/integration/gcp/test_user_agent.py
  tests/unit/deployers/gcp/test_gcp.py
  tests/unit/test_http_utils.py
Labels: approved, lgtm, size/L

#245 Plans for Q2
  roadmap.md
Labels: approved, lgtm, size/S

#247 Add Fairing Prow tests
  cloudbuild.yaml
  fairing/cloud/gcp.py
  prow_config.yaml
  tests/e2e.sh
  tests/unit.sh
  tests/workflows/.ksonnet/registries/incubator/422d521c05aa905df949868143b26445f5e4eda5.yaml
  tests/workflows/.ksonnet/registries/kubeflow/61c7da4756c8ba149637bf4a9e1805258fbead96.yaml
  tests/workflows/app.yaml
  tests/workflows/components/params.libsonnet
  tests/workflows/components/workflows.jsonnet
  tests/workflows/components/workflows.libsonnet
  tests/workflows/environments/base.libsonnet
  tests/workflows/environments/test/.metadata/k.libsonnet
  tests/workflows/environments/test/.metadata/k8s.libsonnet
  tests/workflows/environments/test/.metadata/swagger.json
  tests/workflows/environments/test/main.jsonnet
  tests/workflows/environments/test/params.libsonnet
Labels: approved, lgtm, size/XXL

#249 Bumping the minor version for a release
  fairing/__init__.py
  setup.py
  tests/integration/gcp/test_user_agent.py
Labels: approved, lgtm, size/XS

#252 Added native support for LightGBM
  examples/lightgbm/Dockerfile
  examples/lightgbm/simple-training.ipynb
  fairing/frameworks/__init__.py
  fairing/frameworks/lightgbm.py
  tests/unit/frameworks/test_lightgbm.py
Labels: approved, lgtm, size/L

#259 Added distributed training support for LightGBM
  examples/lightgbm/distributed-training.ipynb
  examples/prediction/requirements.txt
  fairing/frameworks/lightgbm.py
  fairing/frameworks/lightgbm_dist_training_init.py
  fairing/frameworks/utils.py
  fairing/preprocessors/base.py
  tests/integration/gcp/test_running_in_notebooks.py
  tests/unit/frameworks/test_lightgbm.py
Labels: approved, lgtm, size/XL

#261 return job name from deployer
  fairing/config.py
  fairing/deployers/gcp/gcp.py
  fairing/deployers/job/job.py
  fairing/ml_tasks/tasks.py
Labels: approved, lgtm, ok-to-test, size/XS

#262 Added resource specification for pods in LightGBM API
  examples/lightgbm/distributed-training.ipynb
  fairing/frameworks/lightgbm.py
  fairing/frameworks/utils.py
  fairing/kubernetes/utils.py
  tests/unit/kubernetes/test_utils.py
Labels: approved, lgtm, priority/p1, size/L

#264 Updating gsutil config to improve speed
  examples/lightgbm/Dockerfile
Labels: approved, lgtm, size/S

#267 LightGBM - Copies weight file if it exists
  fairing/cloud/storage.py
  fairing/frameworks/lightgbm.py
  tests/integration/gcp/test_running_in_notebooks.py
  tests/unit/frameworks/test_lightgbm.py
Labels: approved, lgtm, size/L

#266 Support hostname as a serving endpoint
  fairing/kubernetes/manager.py
Labels: approved, lgtm, ok-to-test, size/XS
