Repository kubeflow/fairing, pull requests merged in 2019-08, with the labels that each got.

#334 Add logging to preprocessor.
  fairing/preprocessors/converted_notebook.py
Labels: approved, lgtm, size/XS

#337 fix integration tests problem
  tests/e2e.sh
Labels: approved, lgtm, size/XS

#331 fix mini message problems in conf
  fairing/config.py
Labels: approved, lgtm, size/XS

#325 support mounting pvc for job deployer
  fairing/backends/backends.py
  fairing/constants/constants.py
  fairing/kubernetes/utils.py
  fairing/ml_tasks/tasks.py
  tests/integration/onprem/test_pvc_mounting.py
Labels: approved, lgtm, size/L

#339 Changes for #323
  fairing/preprocessors/function.py
Labels: approved, lgtm, ok-to-test, size/XS

#343 Disabling a test that is causing a timeout in the presubmit tests
  tests/integration/gcp/test_gcs_access.py
Labels: approved, lgtm, size/S

#345 update owner for jinchihe
  OWNERS
Labels: approved, lgtm, size/XS

#322 Azure backend support
  Dockerfile.test
  cloudbuild.yaml
  examples/prediction/xgboost-high-level-apis.ipynb
  fairing/backends/backends.py
  fairing/builders/cluster/azurestorage_context.py
  fairing/cloud/azure.py
  fairing/constants/constants.py
  fairing/kubernetes/manager.py
  fairing/ml_tasks/tasks.py
  requirements.txt
  tests/integration/azure/test_azure_file_uploader.py
  tests/integration/azure/test_running_in_notebooks.py
  tests/integration/gcp/test_gcp_high_level_apis.py
  tests/integration/gcp/test_running_in_notebooks.py
  tests/integration/helpers.py
  tests/unit/cloud/test_azure.py
Labels: approved, lgtm, ok-to-test, size/XL

#335 Fix bug in predict in examples.
  Dockerfile.test
  examples/prediction/HousingServe.py
  examples/prediction/requirements.txt
  examples/prediction/xgboost-gkeop.ipynb
  examples/prediction/xgboost-high-level-apis.ipynb
  examples/prediction/xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb
  requirements.txt
  tests/e2e.sh
Labels: approved, lgtm, size/M

#348 Disable istio injection for builder
  fairing/builders/cluster/cluster.py
Labels: approved, lgtm, ok-to-test, size/XS

#358 Updating issue bot configs
  .github/issue_label_bot.yaml
Labels: approved, lgtm, ok-to-test, size/XS
