Repository kubeflow/fairing, pull requests merged in 2019-07, with the labels that each got.

#305 Better error message when tf-job version mismatch
  fairing/kubernetes/manager.py
Labels: approved, lgtm, size/S

#299 support kfserving in fairing
  examples/kfserving/main.py
  fairing/config.py
  fairing/constants/constants.py
  fairing/deployers/kfserving/__init__.py
  fairing/deployers/kfserving/kfserving.py
  fairing/kubernetes/manager.py
  tests/unit/deployers/kfserving.py
Labels: approved, lgtm, size/L

#313 Upgrading ks version for e2e testing
  tests/workflows/app.yaml
Labels: approved, lgtm, size/XS

#317 Specifying exact container while log tailing
  Dockerfile.test
  fairing/builders/cluster/cluster.py
  fairing/deployers/job/job.py
  fairing/deployers/tfjob/tfjob.py
Labels: approved, lgtm, size/S

#311 Add a option to let user cleanup tfjob
  fairing/deployers/tfjob/tfjob.py
  fairing/kubernetes/manager.py
  tests/integration/common/test_kubeflow_training.py
Labels: approved, lgtm, size/M

#310 add preprocessor to convert notebook to code
  fairing/preprocessors/converted_notebook.py
  tests/unit/preprocessors/test_converted_notebook_preprocessor.py
  tests/unit/preprocessors/test_notebook.ipynb
  tests/unit/preprocessors/test_notebook.py
Labels: approved, lgtm, ok-to-test, size/L

#318 Defaulting to current namespace instead of kubeflow namespace and other minor changes
  examples/prediction/xgboost-high-level-apis.ipynb
  fairing/backends/backends.py
  fairing/builders/cluster/cluster.py
  fairing/builders/cluster/gcs_context.py
  fairing/frameworks/lightgbm.py
  fairing/ml_tasks/tasks.py
  tests/integration/common/test_kubeflow_training.py
Labels: approved, lgtm, size/M

#321 fix one message issue and classify constants
  fairing/constants/constants.py
  fairing/deployers/job/job.py
  fairing/deployers/serving/serving.py
Labels: approved, lgtm, size/S

#320 Avoid converting to different path if running preprocessor multiple times
  fairing/preprocessors/converted_notebook.py
  tests/unit/preprocessors/test_converted_notebook_preprocessor.py
Labels: approved, lgtm, size/M

#327 support pod_spec_mutators in Serving deployer
  fairing/deployers/serving/serving.py
Labels: approved, lgtm, size/XS
