Repository kubeflow/fairing, pull requests merged in 2019-12, with the labels that each got.

#429 Correct the function's output alert message.
  kubeflow/fairing/config.py
Labels: approved, lgtm, size/XS

#431 Avoid import Imputer error for different sklearn verions
  examples/notebook/deploy-to-gcp.ipynb
  examples/notebook/fairing-xgboost.ipynb
  examples/prediction/HousingTrain.py
  examples/prediction/xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb
Labels: approved, lgtm, ok-to-test, size/S

#433 Fix remote_train issue in xgboost-train
  examples/prediction/Dockerfile
  examples/prediction/requirements.txt
Labels: approved, lgtm, ok-to-test, size/XS
