Repository kubeflow/fairing, pull requests merged in 2019-06, with the labels that each got.

#269 add backofflimit to avoid job recreation
  fairing/deployers/job/job.py
Labels: approved, lgtm, ok-to-test, size/XS

#270 Added issue/pr template.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/M

#272 add name to container
  fairing/deployers/job/job.py
Labels: approved, lgtm, ok-to-test, size/XS

#276 Added support for data parallel mode in LightGBM
  examples/lightgbm/distributed-training-data-parallel.ipynb
  fairing/frameworks/lightgbm.py
  fairing/frameworks/lightgbm_dist_training_init.py
  fairing/frameworks/utils.py
  tests/unit/frameworks/test_lightgbm.py
Labels: approved, lgtm, size/L

#241 PyTorch notebook examples
  examples/pytorch/mnist/mnist.ipynb
  examples/pytorch/mnist/requirements.txt
Labels: approved, lgtm, size/L

#279 Adding different entry point options to Train Job API
  examples/train_job_api/main.ipynb
  examples/train_job_api/train.ipynb
  fairing/backends/backends.py
  fairing/cloud/gcp.py
  fairing/ml_tasks/tasks.py
  fairing/ml_tasks/utils.py
  fairing/preprocessors/base.py
  fairing/preprocessors/function.py
  tests/unit/preprocessors/test_notebook.py
Labels: approved, lgtm, size/L

#280 Minor bug fix in TrainJob API
  fairing/ml_tasks/tasks.py
  fairing/ml_tasks/utils.py
Labels: approved, lgtm, size/XS

#278 remove useless set_model
  examples/kubeflow/main.py
  examples/kubernetes-in-cluster-builder/main.py
Labels: approved, lgtm, size/XS

#281 Add ability to specify context_source for k8s backends
  fairing/backends/backends.py
  fairing/builders/cluster/cluster.py
  tests/integration/common/test_kubeflow_training.py
Labels: approved, lgtm, ok-to-test, size/S

#285 update examples to add set_preprocessor
  examples/distributed-training/main.py
  examples/gcp/hello-world-gpu-pytorch.py
  examples/kubeflow-gke/main.py
  examples/kubeflow/main.py
  examples/kubernetes-in-cluster-builder/main.py
  examples/kubernetes/main.py
Labels: approved, lgtm, size/M

#291 Check python version for function preprocessor
  fairing/functions/function_shim.py
  fairing/preprocessors/function.py
  tests/integration/common/test_py_version_checking.py
Labels: approved, lgtm, size/M

#263 Implement AWSBackend and S3Context
  fairing/backends/backends.py
  fairing/builders/cluster/s3_context.py
  fairing/cloud/aws.py
  fairing/constants/constants.py
  fairing/kubernetes/manager.py
  requirements.txt
Labels: approved, lgtm, ok-to-test, size/L

#292 Warn users who are using function preprocessor and not in notebook
  fairing/preprocessors/function.py
Labels: approved, lgtm, size/XS

#301 Add xgboost example for gke on prem
  examples/prediction/xgboost-gkeop.ipynb
Labels: approved, lgtm, size/L

#294 allow user input service type
  fairing/backends/backends.py
  fairing/ml_tasks/tasks.py
Labels: approved, lgtm, size/S

#297 upgrade tfjobs version
  examples/prediction/xgboost-high-level-apis.ipynb
  fairing/constants/constants.py
  fairing/deployers/tfjob/tfjob.py
  fairing/kubernetes/manager.py
Labels: approved, lgtm, size/M

#303 add jinchihe to owners
  OWNERS
Labels: approved, lgtm, size/XS

#306 fix notebook for gke on prem
  examples/prediction/xgboost-gkeop.ipynb
Labels: approved, lgtm, size/S
