Repository kubeflow/fairing, pull requests merged in 2019-04, with the labels that each got.

#157 Add prediction client
  examples/prediction/xgboost-high-level-apis.ipynb
  examples/prediction/xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb
  fairing/deployers/serving/serving.py
  fairing/kubernetes/manager.py
  fairing/ml_tasks/tasks.py
Labels: approved, lgtm, priority/p0, size/M

#165 create bucket if it doesnt exist
  fairing/cloud/gcp.py
Labels: approved, lgtm, size/S

#162 Update full_notebook preprocessor to use Papermill
  fairing/preprocessors/base.py
  fairing/preprocessors/full_notebook.py
  tests/integration/common/test_full_notebook.py
  tests/integration/common/test_notebook.ipynb
  tests/unit/preprocessors/test_full_notebook_preprocessor.py
  tests/unit/preprocessors/test_notebook.ipynb
Labels: approved, lgtm, size/L

#168 v0.5 cherrypicks
  examples/prediction/xgboost-high-level-apis.ipynb
  examples/prediction/xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb
  fairing/cloud/gcp.py
  fairing/deployers/serving/serving.py
  fairing/kubernetes/manager.py
  fairing/ml_tasks/tasks.py
Labels: approved, lgtm, size/M

#169 Updating authors and description in setup.py
  setup.py
Labels: approved, lgtm, size/XS

#170 Cherry-picks from master and updates to version number
  setup.py
Labels: approved, lgtm, size/S

#175 Default Kubeflow backends to Job
  fairing/backends/backends.py
Labels: approved, lgtm, size/XS

#177 call get_service_external_endpoint correctly
  fairing/deployers/serving/serving.py
Labels: approved, kind/bug, lgtm, priority/p0, size/XS

#171 Update full notebook tests and convert absolute to relative paths
  fairing/preprocessors/full_notebook.py
  tests/integration/common/requirements.txt
  tests/integration/common/test_full_notebook.py
  tests/unit/preprocessors/test_full_notebook_preprocessor.py
Labels: approved, lgtm, size/M

#178 Add unique label to cluster builder job
  fairing/builders/cluster/cluster.py
Labels: approved, lgtm, size/XS

#172 Add job config to GCP deployer
  fairing/deployers/gcp/gcp.py
  tests/unit/deployers/gcp/test_gcp.py
Labels: approved, lgtm, size/L

#180 Adding necessary pod spec mutators to cluster builder in the high level api
  Dockerfile.test
  cloudbuild.yaml
  examples/prediction/xgboost-high-level-apis.ipynb
  fairing/backends/backends.py
  fairing/deployers/serving/serving.py
  fairing/ml_tasks/tasks.py
  fairing/ml_tasks/utils.py
  tests/integration/gcp/test_running_in_notebooks.py
Labels: approved, lgtm, priority/p0, size/L

#182 Adding myself to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#181 Fix prediction
  examples/prediction/xgboost-high-level-apis.ipynb
  examples/prediction/xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb
  fairing/ml_tasks/tasks.py
Labels: approved, lgtm, priority/p0, size/M

#186 updated requirements for Kubernetes client lib
  requirements.txt
Labels: approved, lgtm, size/XS

#187 Test improvements and minor fixes for storage client auth
  .gitignore
  Dockerfile.test
  fairing/cloud/gcp.py
  requirements.txt
  tests/integration/common/test_high_level_apis.py
  tests/integration/common/test_kubeflow_training.py
  tests/integration/gcp/test_gcp_high_level_apis.py
  tests/integration/gcp/test_gcs_access.py
Labels: approved, lgtm, size/M

#188 Bumping version to 0.5
  setup.py
Labels: approved, lgtm, size/XS

#190 Adds process descriptions to xgboost-high-level-apis.ipynb.
  examples/prediction/xgboost-high-level-apis.ipynb
Labels: approved, lgtm, size/M

#192 add build version
  setup.py
Labels: approved, size/XS

#193 cut v0.5.2
  setup.py
Labels: size/XS

#205 Add labels to deployment
  fairing/deployers/job/job.py
Labels: approved, lgtm, size/XS

#211 Create issue_label_bot.yaml
  .github/issue_label_bot.yaml
Labels: approved, lgtm, size/XS

#210 Remove rpasricha from owners file
  OWNERS
Labels: approved, lgtm, size/XS

#214 update documentation on xgboost example notebook
  examples/prediction/xgboost-high-level-apis.ipynb
Labels: approved, lgtm, size/XS

#207 Add logging, set working directory and service type.
  fairing/builders/append/append.py
  fairing/builders/base_builder.py
  fairing/builders/cluster/cluster.py
  fairing/builders/docker/docker.py
  fairing/config.py
  fairing/deployers/serving/serving.py
  fairing/ml_tasks/tasks.py
  fairing/preprocessors/base.py
Labels: approved, lgtm, size/M

#215 Fix a typo in reference to service_type to fix postsubmit tests
  fairing/deployers/serving/serving.py
Labels: approved, lgtm, size/XS

#220 placeholder prow config
  prow_config.yaml
Labels: approved, lgtm, size/XS

#189 Integrate GCP Serving deployer with deployer interface
  fairing/deployers/gcp/gcpserving.py
  tests/unit/deployers/gcp/test_gcpserving.py
Labels: approved, lgtm, size/M

#231 Updates readme.md to refer users to the docs site
  README.md
Labels: approved, lgtm, size/L
