Repository kubeflow/fairing, pull requests merged in 2019-10, with the labels that each got.

#390 add docstring for backends
  kubeflow/fairing/backends/backends.py
Labels: approved, lgtm, ok-to-test, size/L

#389 Add the code comment
  kubeflow/fairing/preprocessors/base.py
Labels: approved, lgtm, size/M

#391 Add the comments
  kubeflow/fairing/preprocessors/full_notebook.py
Labels: approved, lgtm, size/S

#392 Add the comments for the python API functions.
  kubeflow/fairing/preprocessors/function.py
Labels: approved, lgtm, size/S

#386 #383 Use absolute paths
  kubeflow/fairing/__init__.py
  kubeflow/fairing/backends/__init__.py
  kubeflow/fairing/backends/backends.py
  kubeflow/fairing/builders/append/append.py
  kubeflow/fairing/builders/base_builder.py
  kubeflow/fairing/builders/cluster/azurestorage_context.py
  kubeflow/fairing/builders/cluster/cluster.py
  kubeflow/fairing/builders/cluster/gcs_context.py
  kubeflow/fairing/builders/cluster/s3_context.py
  kubeflow/fairing/builders/docker/docker.py
  kubeflow/fairing/builders/dockerfile.py
  kubeflow/fairing/cloud/aws.py
  kubeflow/fairing/cloud/azure.py
  kubeflow/fairing/cloud/docker.py
  kubeflow/fairing/cloud/gcp.py
  kubeflow/fairing/config.py
  kubeflow/fairing/deployers/gcp/gcp.py
  kubeflow/fairing/deployers/gcp/gcpserving.py
  kubeflow/fairing/deployers/job/job.py
  kubeflow/fairing/deployers/kfserving/kfserving.py
  kubeflow/fairing/deployers/serving/serving.py
  kubeflow/fairing/deployers/tfjob/tfjob.py
  kubeflow/fairing/frameworks/lightgbm.py
  kubeflow/fairing/http_utils.py
  kubeflow/fairing/kubernetes/manager.py
  kubeflow/fairing/kubernetes/utils.py
  kubeflow/fairing/ml_tasks/tasks.py
  kubeflow/fairing/ml_tasks/utils.py
  kubeflow/fairing/preprocessors/base.py
  kubeflow/fairing/preprocessors/converted_notebook.py
  kubeflow/fairing/preprocessors/full_notebook.py
  kubeflow/fairing/preprocessors/function.py
  tests/integration/common/test_high_level_apis.py
Labels: approved, lgtm, ok-to-test, size/L

#395 Fix Gcp creds for workload identity
  examples/prediction/xgboost-high-level-apis.ipynb
  kubeflow/fairing/backends/backends.py
  kubeflow/fairing/builders/cluster/gcs_context.py
  kubeflow/fairing/cloud/gcp.py
  kubeflow/fairing/constants/constants.py
  kubeflow/fairing/deployers/job/job.py
  tests/integration/gcp/test_gcp_high_level_apis.py
Labels: approved, lgtm, size/M

#398 Move kaniko image to constants
  kubeflow/fairing/builders/cluster/azurestorage_context.py
  kubeflow/fairing/builders/cluster/gcs_context.py
  kubeflow/fairing/builders/cluster/s3_context.py
  kubeflow/fairing/constants/constants.py
Labels: approved, lgtm, ok-to-test, size/S

#399 Upgrade presubmits CI cluster to 0.7
  cloudbuild.yaml
  examples/lightgbm/distributed-training.ipynb
  kubeflow/fairing/constants/constants.py
  kubeflow/fairing/deployers/job/job.py
  tests/integration/common/test_full_notebook.py
  tests/integration/common/test_kubeflow_training.py
  tests/integration/gcp/test_gcp_high_level_apis.py
  tests/integration/gcp/test_gcs_access.py
Labels: approved, lgtm, size/M

#402 docString for cloud aws
  kubeflow/fairing/cloud/aws.py
Labels: approved, lgtm, ok-to-test, size/M

#401 Add doc to notebook
  kubeflow/fairing/notebook/notebook_util.py
Labels: approved, lgtm, size/XS

#397 Pass pod_spec_mutators to builder BaseTask class
  kubeflow/fairing/ml_tasks/tasks.py
Labels: approved, lgtm, ok-to-test, size/XS

#396 add member comments to some methods
  kubeflow/fairing/builders/append/append.py
  kubeflow/fairing/builders/base_builder.py
  kubeflow/fairing/builders/builder.py
  kubeflow/fairing/builders/cluster/azurestorage_context.py
  kubeflow/fairing/builders/cluster/cluster.py
  kubeflow/fairing/builders/cluster/context_source.py
  kubeflow/fairing/builders/cluster/gcs_context.py
  kubeflow/fairing/builders/cluster/s3_context.py
  kubeflow/fairing/builders/docker/docker.py
  kubeflow/fairing/builders/dockerfile.py
Labels: approved, lgtm, ok-to-test, size/M

#400 Add doc into ml_task
  kubeflow/fairing/ml_tasks/tasks.py
  kubeflow/fairing/ml_tasks/utils.py
  kubeflow/fairing/notebook/notebook_util.py
Labels: approved, lgtm, size/M

#405 Allow setting custom Dockerfile for ClusterBuilder
  kubeflow/fairing/builders/cluster/cluster.py
  kubeflow/fairing/builders/docker/docker.py
  kubeflow/fairing/builders/dockerfile.py
  tests/integration/common/Dockerfile.test
  tests/integration/common/test_kubeflow_training.py
Labels: approved, lgtm, size/M
