Repository kubeflow/fairing, pull requests merged in 2019-02, with the labels that each got.

#66 Format
  fairing/__init__.py
  fairing/builders/__init__.py
  fairing/builders/append/__init__.py
  fairing/builders/append/append.py
  fairing/builders/base_builder.py
  fairing/builders/builder.py
  fairing/builders/cluster/__init__.py
  fairing/builders/cluster/cluster.py
  fairing/builders/cluster/context_source.py
  fairing/builders/cluster/gcs_context.py
  fairing/builders/docker/__init__.py
  fairing/builders/docker/docker.py
  fairing/builders/dockerfile.py
  fairing/cloud/gcp.py
  fairing/config.py
  fairing/constants/constants.py
  fairing/deployers/__init__.py
  fairing/deployers/deployer.py
  fairing/deployers/job/job.py
  fairing/deployers/tfjob/tfjob.py
  fairing/kubernetes/__init__.py
  fairing/kubernetes/manager.py
  fairing/notebook/notebook_util.py
  fairing/preprocessors/__init__.py
  fairing/preprocessors/base.py
  fairing/preprocessors/converted_notebook.py
  fairing/preprocessors/full_notebook.py
  fairing/runtime_config.py
  fairing/utils.py
Labels: approved, lgtm, size/L

#70 Add rpasricha to Fairing reviewers
  OWNERS
Labels: approved, lgtm, needs-ok-to-test, size/XS

#72 Updating approvers list
  OWNERS
Labels: approved, lgtm, size/XS

#67 Add push switch to builders
  Dockerfile
  fairing/builders/append/append.py
  fairing/builders/base_builder.py
  fairing/builders/cluster/cluster.py
  fairing/builders/cluster/gcs_context.py
  fairing/builders/docker/docker.py
  fairing/kubernetes/manager.py
Labels: approved, lgtm, size/M

#68 Add a basic function preprocessor
  examples/simple/main.py
  fairing/builders/append/append.py
  fairing/config.py
  fairing/deployers/job/job.py
  fairing/functions/function_shim.py
  fairing/preprocessors/base.py
  fairing/preprocessors/function.py
  fairing/runtime_config.py
Labels: approved, lgtm, size/L

#77 Add Travis setup and Fairing config tests
  .circleci/config.yml
  .travis.yml
  fairing/builders/cluster/cluster.py
  fairing/config.py
  tests/config_test.py
Labels: approved, lgtm, size/M

#85 Modified function preprocessor to use cloudpickle
  examples/notebook/hello-world.ipynb
  examples/simple/main.py
  fairing/config.py
  fairing/functions/__init__.py
  fairing/functions/function_shim.py
  fairing/notebook/notebook_util.py
  fairing/preprocessors/function.py
  requirements.txt
  tests/preprocessors/test_function_preprocessor.py
Labels: approved, lgtm, size/L

#86 Add GCP deployer
  fairing/builders/append/append.py
  fairing/config.py
  fairing/deployers/gcp/__init__.py
  fairing/deployers/gcp/gcp.py
  fairing/utils.py
  requirements.txt
Labels: approved, lgtm, size/M
