Repository kubeflow/fairing, pull requests merged in 2019-03, with the labels that each got.

#92 Add cloud build Dockerfile and build steps
  .dockerignore
  Dockerfile.test
  cloudbuild.yaml
Labels: approved, lgtm, size/L

#91 Add Serving Deployer
  examples/prediction/HousingServe.py
  examples/prediction/HousingTrain.py
  examples/prediction/README.md
  examples/prediction/ames_dataset/data_description.txt
  examples/prediction/ames_dataset/sample_submission.csv
  examples/prediction/ames_dataset/test.csv
  examples/prediction/ames_dataset/train.csv
  examples/prediction/requirements.txt
  examples/prediction/trained_ames_model.dat
  fairing/builders/base_builder.py
  fairing/builders/cluster/cluster.py
  fairing/builders/docker/docker.py
  fairing/builders/dockerfile.py
  fairing/config.py
  fairing/deployers/serving/__init__.py
  fairing/deployers/serving/serving.py
  fairing/kubernetes/manager.py
  fairing/preprocessors/base.py
  fairing/runtime_config.py
Labels: approved, lgtm, size/XXL

#97 some fixes and improvements
  examples/distributed-training/main.py
  fairing/builders/append/append.py
  fairing/builders/base_builder.py
  fairing/builders/cluster/cluster.py
  fairing/builders/docker/docker.py
  fairing/config.py
  fairing/deployers/job/job.py
  fairing/deployers/tfjob/tfjob.py
Labels: approved, lgtm, needs-ok-to-test, size/M

#98 Removing pining exact versions of the dependencies
  requirements.txt
Labels: approved, lgtm, size/S

#96 explicitly set restart_policy to never for job
  fairing/deployers/job/job.py
Labels: approved, lgtm, size/XS

#103 Check additional locations when retrieving project_id and credentials
  .travis.yml
  fairing/cloud/gcp.py
  tests/cloud/test_gcp_creds.py
Labels: approved, lgtm, size/M

#105 Removing reviewers who are not active
  OWNERS
Labels: approved, lgtm, size/XS

#107 Update readme
  README.md
Labels: approved, lgtm, size/XS

#114 remove set_model/get_model from config
  fairing/config.py
Labels: approved, lgtm, size/XS

#115 update distributed training example
  examples/distributed-training/main.py
Labels: approved, lgtm, size/XS

#113 add custom labels to deployer
  fairing/deployers/job/job.py
  fairing/deployers/serving/serving.py
  fairing/deployers/tfjob/tfjob.py
  fairing/kubernetes/manager.py
Labels: approved, lgtm, needs-ok-to-test, size/S

#117 Update examples
  examples/kubeflow-gke/main.py
  examples/kubernetes/main.py
  examples/notebook/fairing-kubeflow-gke.ipynb
  examples/notebook/fairing-xgboost.ipynb
  examples/notebook/hello-world.ipynb
  examples/prediction/trained_ames_model.dat
  examples/simple/main.py
Labels: approved, lgtm, size/L

#112 Kubeflow credentials, tarfile fixes, unit tests
  .travis.yml
  Dockerfile.test
  cloudbuild.yaml
  fairing/deployers/job/job.py
  fairing/deployers/tfjob/tfjob.py
  fairing/preprocessors/base.py
  fairing/preprocessors/converted_notebook.py
  fairing/preprocessors/full_notebook.py
  fairing/preprocessors/function.py
  tests/integration/test_kubeflow_training.py
  tests/unit/cloud/test_gcp_creds.py
  tests/unit/config_test.py
  tests/unit/preprocessors/test_function_preprocessor.py
Labels: approved, lgtm, size/L

#116 Update to ReadMe.md
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/L

#120 Make prediction endpoint deployment work with function preprocessor in a notebook
  .gitignore
  examples/prediction/Dockerfile
  examples/prediction/requirements.txt
  examples/prediction/xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb
  fairing/deployers/tfjob/tfjob.py
  fairing/functions/function_shim.py
  fairing/preprocessors/base.py
  fairing/preprocessors/function.py
Labels: approved, lgtm, size/L

#130 Adding scale tier as a pass through option to GCP deployer
  examples/gcp/hello-world-gpu-pytorch.py
  fairing/deployers/gcp/gcp.py
Labels: approved, lgtm, size/M

#133 Update README.md
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#132 Setting docker command in docker builder
  fairing/builders/docker/docker.py
  fairing/builders/dockerfile.py
  tests/unit/builders/test_dockerfile.py
Labels: approved, lgtm, size/M

#134 GCP Serving Deployer
  examples/notebook/deploy-to-gcp.ipynb
  fairing/deployers/gcp/gcpserving.py
  tests/unit/deployers/gcp/test_gcpserving.py
Labels: approved, lgtm, size/L

#136 Refactor Service Account Credentials
  fairing/cloud/gcp.py
  fairing/deployers/job/job.py
  fairing/deployers/tfjob/tfjob.py
  fairing/kubernetes/manager.py
  tests/integration/test_kubeflow_training.py
Labels: approved, lgtm, size/L

#138 add more context
  README.md
Labels: approved, lgtm, size/XS

#137 add pod spec mutators for cluster builder
  fairing/builders/cluster/cluster.py
Labels: approved, lgtm, size/S

#140 Jupyter requires tornando lower than 6
  requirements.txt
Labels: approved, lgtm, size/XS

#142 Full notebook preprocessor updates
  fairing/preprocessors/base.py
  fairing/preprocessors/full_notebook.py
Labels: approved, lgtm, size/M

#147 lint the examples a bit
  examples/kubeflow-gke/main.py
  examples/kubeflow/main.py
  examples/kubernetes-in-cluster-builder/main.py
  examples/kubernetes/main.py
Labels: approved, lgtm, size/M

#151 Adding code coverage for pytest tests
  Dockerfile.test
  cloudbuild.yaml
  setup.py
  tests/__init__.py
  tests/integration/__init__.py
  tests/unit/__init__.py
Labels: approved, lgtm, size/XS

#158 Installing requirements earlier and fixing issues with cluster builder
  fairing/builders/cluster/cluster.py
  fairing/builders/cluster/gcs_context.py
  fairing/builders/docker/docker.py
  fairing/builders/dockerfile.py
  fairing/preprocessors/base.py
  tests/integration/common/test_kubeflow_training.py
  tests/unit/builders/test_dockerfile.py
  tests/unit/preprocessors/test_base_preprocessor.py
Labels: approved, lgtm, size/L

#159 Skip creating secret in context preparer
  fairing/builders/cluster/gcs_context.py
Labels: approved, lgtm, size/M
