Repository kubeflow/fairing, pull requests merged in 2020-09, with the labels that each got.

#536 Add conditional statement to dockerfile considering user of base image
  kubeflow/fairing/builders/cluster/cluster.py
  kubeflow/fairing/builders/docker/docker.py
  kubeflow/fairing/builders/dockerfile.py
  kubeflow/fairing/builders/podman/podman.py
  tests/unit/builders/test_dockerfile.py
Labels: approved, lgtm, ok-to-test, size/M

#541 Fix for failing Training Job on py 3.8+
  kubeflow/fairing/preprocessors/function.py
Labels: approved, lgtm, ok-to-test, size/S

#542 Fix dockerfile processing behavior of cluster builder
  kubeflow/fairing/builders/cluster/cluster.py
Labels: approved, lgtm, ok-to-test, size/XS
