Repository kubeflow/fairing, pull requests merged in 2020-04, with the labels that each got.

#476 Update roadmap for 2020
  roadmap.md
Labels: approved, lgtm, size/S

#482 Updates Azure Requirements
  requirements.txt
Labels: approved, lgtm, ok-to-test, size/XS

#484 Modify cluster builder example with minio context
  examples/kubernetes-in-cluster-builder/main.py
  examples/kubernetes-in-cluster-builder/requirements.txt
Labels: approved, lgtm, ok-to-test, size/M

#485 Release kubeflow-fairing 0.7.2
  kubeflow/fairing/__init__.py
  setup.py
Labels: approved, lgtm, size/XS

#483 Add functions to apply Kubernetes objects
  kubeflow/fairing/kubernetes/manager.py
  kubeflow/fairing/utils.py
  tests/integration/kubernetes/__init__.py
  tests/integration/kubernetes/test_buck_apply.py
Labels: approved, lgtm, size/L

#488 Support specifying GPU resource
  kubeflow/fairing/kubernetes/utils.py
  tests/unit/kubernetes/test_utils.py
Labels: approved, lgtm, size/S
