Repository kubeflow/fairing, pull requests merged in 2020-01, with the labels that each got.

#438 Fix problem connect breaken
  kubeflow/fairing/kubernetes/manager.py
  requirements.txt
Labels: approved, lgtm, size/XS

#435 Using Kubeflow-tfjob SDK to deploy TFJob
  kubeflow/fairing/deployers/tfjob/tfjob.py
  kubeflow/fairing/kubernetes/manager.py
  requirements.txt
Labels: approved, lgtm, size/M

#436 Support deploying pytorchjob using Kubeflow Fairing
  kubeflow/fairing/config.py
  kubeflow/fairing/constants/constants.py
  kubeflow/fairing/deployers/pytorchjob/__init__.py
  kubeflow/fairing/deployers/pytorchjob/pytorchjob.py
  kubeflow/fairing/kubernetes/manager.py
  requirements.txt
  tests/integration/common/test_kubeflow_training.py
Labels: approved, lgtm, size/L

#443 Reset CI tests to ensure stability
  cloudbuild.yaml
  tests/integration/gcp/test_running_in_notebooks.py
Labels: approved, lgtm, size/XS

#445 executable passed to preprocessing should be treated as input file
  kubeflow/fairing/preprocessors/base.py
Labels: approved, lgtm, ok-to-test, size/XS

#444 Feature/add streaming logging for aiplatform
  examples/gcp/hello-world-gpu-pytorch.py
  kubeflow/fairing/backends/backends.py
  kubeflow/fairing/deployers/gcp/gcp.py
  requirements.txt
Labels: approved, lgtm, ok-to-test, size/M

#442 Refresh the deploy service process.
  examples/prediction/README.md
Labels: approved, lgtm, size/XS

#446 Release kubeflow-fairing 0.7.1
  setup.py
Labels: approved, lgtm, size/XS
