Repository kubeflow/fairing, pull requests merged in 2020-03, with the labels that each got.

#471 Fix duplicated code in cluster builder
  kubeflow/fairing/builders/cluster/minio_context.py
  kubeflow/fairing/builders/cluster/s3_context.py
Labels: approved, lgtm, size/S

#467 Support user specified kubeconfig for remote k8s cluster in deployer
  kubeflow/fairing/deployers/job/job.py
  kubeflow/fairing/deployers/kfserving/kfserving.py
  kubeflow/fairing/deployers/pytorchjob/pytorchjob.py
  kubeflow/fairing/deployers/tfjob/tfjob.py
  kubeflow/fairing/kubernetes/manager.py
Labels: approved, lgtm, size/L

#447 Enhance the logging info output in the debug model
  kubeflow/fairing/config.py
  kubeflow/fairing/constants/constants.py
  kubeflow/fairing/frameworks/lightgbm_dist_training_init.py
Labels: approved, lgtm, size/S

#477 Only use secure transport mode for new Azure Storage Accounts
  kubeflow/fairing/cloud/azure.py
Labels: approved, lgtm, ok-to-test, size/XS

#479 Support IBM cloud as backend
  kubeflow/fairing/backends/backends.py
  kubeflow/fairing/builders/cluster/cos_context.py
  kubeflow/fairing/cloud/ibm_cloud.py
  kubeflow/fairing/constants/constants.py
  requirements.txt
  tests/unit/cloud/test_ibm_cloud.py
Labels: approved, lgtm, size/L

#474 Add podman builder to support CRI-O runtime
  examples/kubeflow/main_ocp.py
  kubeflow/fairing/builders/podman/__init__.py
  kubeflow/fairing/builders/podman/podman.py
  kubeflow/fairing/config.py
  tests/unit/builders/test_podman.py
Labels: approved, lgtm, ok-to-test, size/L
