Repository kubeflow/fairing, pull requests merged in 2020-02, with the labels that each got.

#458 minio context source for vanilla k8s
  kubeflow/fairing/builders/cluster/minio_context.py
  kubeflow/fairing/cloud/k8s.py
Labels: approved, lgtm, size/L

#466 Fairing supports user specify the deployers name
  kubeflow/fairing/deployers/job/job.py
  kubeflow/fairing/deployers/kfserving/kfserving.py
  kubeflow/fairing/deployers/pytorchjob/pytorchjob.py
  kubeflow/fairing/deployers/tfjob/tfjob.py
Labels: approved, lgtm, size/M

#464 Add Kubeflow Fairing E2E Sample
  README.md
  examples/kfserving/main.py
  examples/mnist/Dockerfile
  examples/mnist/README.md
  examples/mnist/mnist.py
  examples/mnist/mnist_e2e_on_prem.ipynb
Labels: approved, lgtm, size/XXL
