Repository kubeflow/fairing, pull requests merged in 2020-08, with the labels that each got.

#527 Enhance mnist example in Kubeflow Fairing
  examples/mnist/input.json
  examples/mnist/mnist_e2e_on_prem.ipynb
Labels: approved, lgtm, size/XL

#528 add sub_path option to volume_mounts
  kubeflow/fairing/kubernetes/utils.py
Labels: approved, lgtm, ok-to-test, size/XS

#533 fix broken link in README
  README.md
Labels: approved, lgtm, size/XS

#532 update fairing/lightgbm retries to scale with num_machines
  kubeflow/fairing/frameworks/utils.py
Labels: approved, lgtm, ok-to-test, size/S

#534 Add pugangxa as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#535 Release Kubeflow Fairing 1.0.2
  kubeflow/fairing/__init__.py
  setup.py
Labels: approved, lgtm, size/XS
