Repository kubeflow/fairing, pull requests merged in 2020-07, with the labels that each got.

#522 Fix bug for V1alpha2TensorRTSpec ImportError
  kubeflow/fairing/deployers/kfserving/kfserving.py
  requirements.txt
Labels: approved, lgtm, size/S

#515 Support configuring environment variables
  kubeflow/fairing/kubernetes/utils.py
  tests/unit/kubernetes/test_utils.py
Labels: approved, lgtm, size/M

#520 Support mount secret and config map for deployer
  kubeflow/fairing/constants/constants.py
  kubeflow/fairing/kubernetes/utils.py
Labels: approved, lgtm, size/M

#523 Release kubeflow-fairing v1.0.1
  kubeflow/fairing/__init__.py
  setup.py
Labels: approved, lgtm, size/XS

#518 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#524 Fix broken PredictionEndpoint
  kubeflow/fairing/ml_tasks/tasks.py
Labels: approved, lgtm, ok-to-test, size/XS
